### ISSUE TITLE
IOS 8

### ISSUE THREAD

**Issue by mythodeia** [mariohahn/MHDismissModalView#11]
@mariohahn 
first of all thanks for the open source lib, great work.
This library was working just fine on IOS 7. When i upgraded and started testing on IOS 8
the library is behaving weird. It does not allow pan gesture to finish and dismisses the view without animation plus blocking the interface behind it .

Can anyone else confirm?

thanks

**Comment by mythodeia** [comment]
@mariohahn 
i  narrowed it down to this line:
[[[UIApplication sharedApplication] keyWindow] insertSubview:view belowSubview:self.view];

if you uncomment this line it works but the background colour is black

if you leave it as it is then as soon as you touch the view to start scrolling or try to dismiss it by panning the view disappears instantly and you cannot do anything afterwards

thanks

**Comment by mythodeia** [comment]
@mariohahn 
found the problem
UILayoutContainerView in IOS 8 is not 1st view after keyWindow. You can solve this now using this:
this is a small hack to make it work
if you find a better solution please share:

```
        if ([[[UIDevice currentDevice] systemVersion] floatValue ] >= 8) {
            [[[[[UIApplication sharedApplication] keyWindow] subviews] objectAtIndex:0] insertSubview:view belowSubview:self.view];
        }
        else{
            [[[UIApplication sharedApplication] keyWindow] insertSubview:view belowSubview:self.view];
        }
```

if you want a PR let me know
thanks

**Comment by iamchenchen** [comment]
@mythodeia I've encounter the same problem. I'd love if you can have a pull request for this problem.

**Comment by mythodeia** [comment]
@iamchenchen
here you go...https://github.com/mariohahn/MHDismissModalView/pull/12
let me know if it works for you

**Comment by iamchenchen** [comment]
thanks!
