### ISSUE TITLE
MailComposeViewController bug

### ISSUE THREAD

**Issue by uncleho** [mariohahn/MHDismissModalView#3]
If you have a button that does this:
- (IBAction)showEmail:(id)sender {
  // Email Subject
  NSString *emailTitle = @"A message from the GlennKessler app:";
  // Email Content
  NSString *messageBody = @"Dear Glenn Kessler:";
  // To address
  NSArray *toRecipents = [NSArray arrayWithObject:@"adminglennkessler@icloud.com"];
  
  MFMailComposeViewController *mc = [[MFMailComposeViewController alloc] init];
  mc.mailComposeDelegate = self;
  [mc setSubject:emailTitle];
  [mc setMessageBody:messageBody isHTML:NO];
  [mc setToRecipients:toRecipents];
  
  // Present mail view controller on screen
  [self presentViewController:mc animated:YES completion:NULL];

}

When the mail compose window pops up, it temporarily blurs the background, and then fixes it. It shouldn't blur the background.

**Comment by mariohahn** [comment]
Hello 
use a  MHDismissIgnore Object

MHDismissIgnore *withoutScroll = [[MHDismissIgnore alloc] initWithViewControllerName:@"ExampleModalViewWithoutScrollViewController"
                                                                        ignoreBlurEffect:NO
                                                                           ignoreGesture:NO];

**Comment by gavla** [comment]
Hi Chaps just wondering if you know of a way it use a MHDismissIgnore Object globally with modal views such as UIPrintInteractionController   as I can't access a string name and loose delegate notifications when closed with a gesture.
Cheers

**Comment by mariohahn** [comment]
Now it should work.
